name: Run tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  system_update:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Update system
        run: |
          echo Updating system
          sudo apt-get update
          sudo apt-get install -y gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 90
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Custom shell commands
        run: |
          echo "Start repo checkout"
          echo "The ${{ github.repository }} repository has been cloned to the runner."

  build:
    needs: system_update
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Compile
        run: |
          cd test/src
          g++ -o ../bin/tests tests.cpp
          echo Tests compiled
          cd ..
          echo Ready to be run

    
  test:
    needs: build
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: running test
        run: |
          cd bin
          ./tests
        shell: bash
